### ISSUE TITLE
Remote controlled device not selecting/playing the correct composition   ( or was it always broken?)

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#101]
@moritzvieli 

I thought the Network Remote Device feature was working correctly, but if it was before, it's not working now.
Maybe it hasn't worked for quite a while. 
I went back and checked each version to 2.2.3 and it's not working correctly on any version.

When configured correctly, I thought a remotely connected device would select/play the same composition as the master device. 

That isn't happening.

What's working:
The master device can reboot, shutdown, start and stop the currently selected Composition on the remote device

What's not working.
The master device can not select which composition to play on the remote device. The remote device will play whatever composition is currently selected in the Start queue. Selecting a different composition on the master isn't being recognized by the remote.

**Comment by DavidOpgh** [comment]
![20230727_181944.jpg](https://github.com/moritzvieli/rocketshow/assets/104005724/d4017769-3c28-424b-8a1d-3504c75510ea)

This is the terminal on the remote device. The last 4 RPC Call failures happened when I selected different compositions on the master device.

**Comment by moritzvieli** [comment]
Hi @DavidOpgh . Thanks for the report!

I just checked the code and found a possible issue introduced long time ago. But I am not sure, if this really solved the problem. I just released a new version (not a new image) 2.3.3. Could you maybe update your remote device online and check, whether this solves the issue?

Thanks a lot for your feedback!

**Comment by moritzvieli** [comment]
@DavidOpgh Additional hint: The logs are unrelated. If you select a composition on the master device, the compositions on the remote devices are just stopped and within this step, the lighting universe is reset. Seems like no lighting device has been enabled on the remote device and therefore an RPC call fails. The new composition should be selected and played on the remote device, as soon as the composition is played on the master device.

**Comment by DavidOpgh** [comment]
@moritzvieli 
Thanks for the quick reply! 
Yes, running version 2.3.3 on the remote device fixed the issue. The remote device will play the composition selected on the master device.

Thanks for info about the logs. 
Since logging appears to be broken on the latest releases the screen shot was the only feedback I could provide.

**Comment by moritzvieli** [comment]
@DavidOpgh Thanks for your quick test! Yes, have not forgotten about the broken logging feature. I will take a look into it. 👍
