### ISSUE TITLE
Support MIDI program changes and cc commands

### ISSUE THREAD

**Issue by moritzvieli** [moritzvieli/rocketshow#11]

**Comment by moritzvieli** [comment]
Fixed with 2.2.4

**Comment by DavidOpgh** [comment]
I'm looking at version 2.2.5 and I don't see where RS supports Midi program changes and cc commands. Only note on/off

**Comment by moritzvieli** [comment]
@DavidOpgh It's now supported, if a MIDI file or MIDI device sends such commands. I suppose, you're not seeing them when adding actions (e.g. start a composition), correct? You're right, this is still missing. I added the following issue to complete this feature: https://github.com/moritzvieli/rocketshow/issues/72

This will be available soon.

**Comment by DavidOpgh** [comment]
@moritzvieli That is correct. I don't see it implemented when trying to add an action. Thanks for the update.
