### ISSUE TITLE
2.3.8 New Backup/Restore function does not included Designer Project files, custom fixture profiles. 

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#115]
@moritzvieli 
I tried using the backup/restore function in 2.3.8 to move my files from the Pi4 to the Pi5. 

Although the process looked like it was successful I'm not seeing the Designer Project files or my custom fixture profiles in either the backup file or the Pi5.

Is this an oversight or is there some other process to backup/restore these files?

**Comment by moritzvieli** [comment]
@DavidOpgh Indeed. This was an oversight. Just released 2.3.9. Can you please try again? You first need to update both devices and create the backup again. Sorry for the inconvenience. Please let me know, whether it works now. Thanks a lot!

**Comment by DavidOpgh** [comment]
@moritzvieli 
2.3.9 backup/restore function now includes the Designer Project files and and custom fixture profiles. I will close this issue.

I will note: 
on the Pi4 version the text labels for this function don't appear to be reference correctly?
![backup1](https://github.com/user-attachments/assets/8411e4b8-94e5-49cf-befd-e0ac2350dbe8)
![backup2](https://github.com/user-attachments/assets/decdc1f4-84cc-4443-9467-e886a86d58db)

One related issue is the Update window never closes after an update and reboot, you must manually refresh the browser, unlike other similar windows. 
![backup3](https://github.com/user-attachments/assets/e0926738-898e-4c5d-85dc-4caa3f17644a)
