### ISSUE TITLE
Play a composition from the composition editor directly

### ISSUE THREAD

**Issue by moritzvieli** [moritzvieli/RocketShow#126]
Try out a composition, without the need to save it first and switch to the play-tab.

**Comment by moritzvieli** [comment]
@DavidOpgh @rennist This is now available on the test channel. Please let me know, if you find something. Thanks a lot!

**Comment by DavidOpgh** [comment]
I gave it a quick test and found no issues. It's much more convenient to adjust volume levels now. Thanks! 

However, the legend change from % to db is incomplete. 

In addition to making the legend display "db" a calculation needs to be done to show the X^4 curve value which indicates the level of db reduction. 

At maximum volume the value would be 0 db and any reduction in the volume would be shown as a negative db value. Much like it is on the Interactive Demo shown on the link you referenced 

https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by moritzvieli** [comment]
@DavidOpgh I changed the volume sliders to a logarithmic scale to display volumes from -60 to 0 dB and pushed it to the test channel. I think it's fine now, based on the article (I had to read a couple more times to understand fully ;)). What do you think?

**Comment by DavidOpgh** [comment]
@moritzvieli - The changes look good now. 
Unless @rennist has anything to add I think this issue can be closed.

**Comment by rennist** [comment]
this working great in my testing so far.

**Comment by DavidOpgh** [comment]
The only other thing I could think of that would be nice to have (although not absolutely needed) would be the ability to able to change the volume levels during playback.

**Comment by moritzvieli** [comment]
This is now released.

@DavidOpgh Rocket Show is mainly used to playback preconfigured compositions. A volume control to adjust volume during playback could lead to unintended changes, if not secured properly with a warning message or behind another click somehow. If really required (which should not be the case currently, as you mentioned), please open a new issue. Thanks a lot!

**Comment by DavidOpgh** [comment]
Thanks for the update.
