### ISSUE TITLE
New Rocket Show Hardware

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/RocketShow#129]
@moritzvieli I see the website is previewing the new RS Hardware.
It looks very impressive, although I would have preferred XLR balanced audio outputs instead of RCA.
Was there a particular reason why you went with RCA?
 
Care to share what kind of hardware is inside?

**Comment by moritzvieli** [comment]
@DavidOpgh jeah, I prefer balanced XLR as well, but seems like such audio interfaces are quite rare (or expensive) and people in this segment are used to RCA (see the ESI Gigaport EX for example). Regarding the hardware:
- it's a Raspberry Pi 4b with 2 GB ram (maybe upgraded soon) and 128 GB SD card
- Sound is provided by an Amanero I2S Interface equivalent (two times)
- DMX is a generic FTDI chip (learned it from you in another issue :))
- MIDI is provided by a generic chip as well

Maybe I'll open the specs and CAD designs for the case as well for users to build it by themselves.

**Comment by DavidOpgh** [comment]
I have this but haven't tried it out with Rocket Show yet. 
https://www.amazon.com/gp/product/B0CX5K386N

**Comment by moritzvieli** [comment]
@DavidOpgh Thanks for the tipp! Unfortunately, this does not ship to me. I checked other platforms but have not found a similar cable with USB A, only USB C. What's the quality of this cable? Maybe I'll use it in a future version.

**Comment by DavidOpgh** [comment]
I haven't tried it yet so I can comment on the quality.

This is also this
https://www.amazon.com/Devinal-Output-Converter-Amplifier-Speaker/dp/B08YNJ9XVD

**Comment by DavidOpgh** [comment]
@moritzvieli 
Is there a reason you're not going with a Pi 5? 
I would think the difference in cost between the Pi 4 and Pi 5 would be minimal.
And is there a power supply included?

**Comment by moritzvieli** [comment]
@DavidOpgh already decided to switch to a Pi 5. as you mentioned, because it does not cost much more.

**Comment by moritzvieli** [comment]
> I haven't tried it yet so I can comment on the quality.
> 
> This is also this https://www.amazon.com/Devinal-Output-Converter-Amplifier-Speaker/dp/B08YNJ9XVD

Unfortunately also not available in my country. Unfortunately, Amazon does not ship much items to us.

**Comment by DavidOpgh** [comment]
> @DavidOpgh already decided to switch to a Pi 5. as you mentioned, because it does not cost much more.

Excellent. The Pi 5 is significant improvement over the Pi 4
