### ISSUE TITLE
What is the largest size and fastest sd card supported?

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#63]
I'm looking for the largest size and fastest card supported (within the budget) on a Pi 4. 
I tried researching it myself but the results weren't clear. 
I checked here
https://elinux.org/RPi_SD_cards

Currently I'm using a SanDisk Extreme PLUS 32GB card and that might be plenty but I wanted to know if there is a limit.

**Comment by DavidOpgh** [comment]
UPDATE
I'm running 2.2.5 on a SanDisk 128GB Extreme microSDXC UHS-I C10, U3, V30, 4K, A2, Micro SD - SDSQXA1-128G-GN6MA

**Comment by moritzvieli** [comment]
@DavidOpgh We tested until 128 GB. The Raspberry Pi might have some limitations but Rocket Show does not limit the card sizes.

**Comment by DavidOpgh** [comment]
Thanks for the response. 128GB will be way more than I'll ever need.
