### ISSUE TITLE
Audio through HDMI possible?

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#64]
I want RS to play a mp4 video that has audio to have the audio come out through the HDMI port to a TV. 
Is that possible?
Just dropping the video into the composition doesn't give any options for the audio.

And just as a test I added a wav file to the composition to see if any audio could be played through the hdmi output. I had the audio bus configured to the bcm hdmi ports. The composition would immediately hang on play and I would have to reboot.

I verified the video is ok by playing it on a laptop to the TV and it played properly. I used the same cable and TV to connect it to the Pi 4.

**Comment by moritzvieli** [comment]
@DavidOpgh Unfortunately, this is not possible currently. Please refer to https://github.com/moritzvieli/rocketshow/issues/31. I need to test again on the new version.
