### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#71]
I was going to play around with RS on a Pi 3. 
I'd like to know if there is a published changelog so I could see what recent features wouldn't be included.

**Comment by moritzvieli** [comment]
@DavidOpgh You can find the changelog here: https://github.com/moritzvieli/rocketshow/blob/master/dist/currentversion2.xml

Currently, there is no distinction between Pi 3 and Pi 4 feature-wise. The Pi 3 might not be actively maintained somewhen in the future.
