### ISSUE TITLE
MIDI Settings broken

### ISSUE THREAD

**Issue by jelgblad** [moritzvieli/rocketshow#8]
Really like your app!

I'm currently running version `2.2.1`.

There seems to be an issue with the MIDI settings, causing the server to respond with a JSON parse error. The error is happening when the settings are saved after a selection has changed in "MIDI input" or "MIDI output".

Haven't had the time to dig into your code, but from looking at the requests to `/api/system/settings` and comparing a valid request (if 'Save' is clicked before any changes in the form) to a erroneous one, I found that the server expects the properties `midiInDevice` and `midiOutDevice` to be object and not numbers.

When the settings are changed these properties are set to a number value, causing the parse error on the server.

**Valid:**
```
{
  instrumentList: [{uuid: "3f27f072-2334-4290-b00b-eba302e50311", name: "Vocals"},…],
  basePath: "/opt/rocketshow/",
  mediaPath: "media",
  midiPath: "midi",
  audioPath: "audio",
  videoPath: "video",
  midiInDevice: {id: 1, name: "MINI [hw:0,0,0]", vendor: "ALSA (http://www.alsa-project.org)",…},
  midiOutDevice: {id: 67, name: "MINI [hw:0,0,0]", vendor: "ALSA (http://www.alsa-project.org)",…},
...
```

**Server parse error:**
```
{
  instrumentList: [{uuid: "3f27f072-2334-4290-b00b-eba302e50311", name: "Vocals"},…],
  basePath: "/opt/rocketshow/",
  mediaPath: "media",
  midiPath: "midi",
  audioPath: "audio",
  videoPath: "video",
  midiInDevice: 2,
  midiOutDevice: {id: 67, name: "MINI [hw:0,0,0]", vendor: "ALSA (http://www.alsa-project.org)",…},
...
```

**And here is the full error message:**

*JSON parse error: Cannot construct instance of `com.ascargon.rocketshow.midi.MidiDevice` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (2); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.ascargon.rocketshow.midi.MidiDevice` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (2)↵ at [Source: (PushbackInputStream); line: 1, column: 397] (through reference chain: com.ascargon.rocketshow.Settings["midiInDevice"])*

**Comment by moritzvieli** [comment]
@jelgblad I was finally able to reproduce this issue (at least two different MIDI devices need to be available). It's fixed with the latest release (2.3.5) available already.
