### ISSUE TITLE
System\Monitoring\Enable   function ?

### ISSUE THREAD

**Issue by rennist** [moritzvieli/rocketshow#84]
Can anyone tell me what the 'System\Monitoring\Enable' checkbox does?   I have tried it on and off can can't see what it does.

Thanks

![image](https://user-images.githubusercontent.com/104380717/228351770-cf4e82c4-c2df-469d-981c-fa7b91356169.png)

**Comment by moritzvieli** [comment]
@rennist If activated, the dots here start to flash if there is MIDI in/out, audio out or light out activity:
![image](https://github.com/moritzvieli/rocketshow/assets/16817802/a089cf94-1a1c-4053-b759-acc88f47af1a)

This comes at a significant performance cost. Therefore it's not recommended to keep it activated for live shows, only during setup-phase.
