### ISSUE TITLE
gstreamer error with default composition using 2.2.6

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#85]
Looks like whatever changes you made to gstreamer for 2.2.6 has somehow affected the playing of the default composition. In 2.2.6 the video file plays correctly as a stand alone composition. But when selected as the default composition it throws an error which also causes RS to hang and can't be recovered.

I've uploaded the video I'm using. 

I tested on three different systems

I tested it with 2.2.5 and the same video file has no issues as the default composition. 

Here is the error message on the console.

Any way to remove the default composition from the command line? I'd rather not have to rebuild these systems from scratch. 

![20230418_194522.jpg](https://user-images.githubusercontent.com/104005724/232928500-545eaf52-668c-46dc-8a13-655255b527af.jpg)

https://user-images.githubusercontent.com/104005724/232933218-28012af9-68be-4e59-9930-647296fd3cce.mp4

**Comment by DavidOpgh** [comment]
![20230418_202210.jpg](https://user-images.githubusercontent.com/104005724/232934724-d98ff368-c908-4c0a-8049-e1ada3d198af.jpg)

**Comment by moritzvieli** [comment]
@DavidOpgh Thanks a lot for the report! There was indeed an update of the Gstreamer base libraries with the new image. I need to take a detailed look into it.

As a workaround yes, you can remove the default composition in the command line: Go to the folder `/opt/rocketshow` and open the settings file using `nano settings.xml`. Now you need to remove the line with `<defaultComposition>xy...` and save the file. If you restart Rocket Show, it should be gone.

**Comment by DavidOpgh** [comment]
@moritzvieli 

Thanks the info. 
Is the Gstreamer update also related to issue #82 ?

**Comment by moritzvieli** [comment]
@DavidOpgh Yes, this issue seems to be resolved as well with #82.
