### ISSUE TITLE
can Pi Desktop be run with Rocketshow?

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#86]
To make it easier to access the Pi4 I wanted to use the desktop, 
either from my attached keyboard/mouse or remote in from my laptop. 
I enabled the VNC Server but I couldn't enable the desktop.

It possible to use the desktop with Rocketshow?

**Comment by DavidOpgh** [comment]
I went in another direction and installed WinSCP on my laptop that gives me the functionality I was looking for to access the files on the Pi 4

**Comment by moritzvieli** [comment]
In general, Rocket Show is also compatible with the desktop version of the pi OS, but there is no dedicated image provided. You would need to install the dependencies and the app manually.

Glad you found a suitable way for you.
