### ISSUE TITLE
Issues with default composition in 2.3.1

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#88]
What is fixed
1080 video files can be added to compositions. 
DMX Fade In/Out on real fixtures.

What is broken
Assigning a default composition breaks Rocket Show

What I observed.
When you assign a composition as the default composition (in my case the default composition consisted of a video file, no audio) 
you won't be able to play any Composition which was synced with a Designer project. So you can't sync DMX lighting with your Composition.

Assigning a default composition also seems to make the dispatcherServlet service hanging up for 1 minute before allowing remote access. So you won't be able to connect remotely to Rocket Show for about 1 minute.

My testing
I created a new build of 2.3.1 and did not specify a default composition until everything else was working correctly. 
I first created a new composition with the default media included with Rocket Show, then create a synced Designer project, and was able to play them successfully.
I then created a 2nd composition, this time with new media I imported, created a synced Designer project, and was able to sync and play them successfully.

Rocket Show worked correctly up until this point.

I then tested what happened when you assigned a default composition to Rocket Show.
The default composition was a new composition consisting of a video file, no audio, then assigned as the default composition. 

This is where Rocket Show would break.
I might be able to play a synced composition once or twice but after that the Designer project wouldn't play. 
If I removed the default composition a synced composition might continue to fail once or twice but after that the Designer project would play every time. 

Rebooting Rocket Show showed the issues immediately.
Rebooting after setting or resetting the default composition caused the synced compositions to work (no default composition set) or fail (default composition set) immediately.

Additional issue with remote access
Any time I rebooted after setting or resetting the default composition caused the dispatcherServlet service to hang up for 1 minute before allowing remote access.
If I rebooted a 2nd time the dispatcherServlet service allowed me remote access almost immediately.

**Comment by moritzvieli** [comment]
@DavidOpgh I found the bug and created a new image (2.3.2). Can you try this one and let me know, whether it works now or nor?

I have not found any issues with the dispatcherServlet however. The only thing fixed is the designer in combination with a default composition.

**Comment by DavidOpgh** [comment]
@moritzvieli  - That's great news! Thanks for the update. I'm looking forward to trying it out.  I will try to do a preliminary test later today. If I run into any issues it will be a few days before I can do any in depth analysis.

**Comment by DavidOpgh** [comment]
@moritzvieli - 

Short answer: 
I have confirmed that 2.3.2 appears to have fixed the default composition / designer issue. 

Longer answer: 
2.3.2 appears to have fixed the default composition / designer issue. However I was getting some new behavior / status messages when configuring the system from scratch. I didn't take any photos of the behavior/ status messages at the time and I haven't been able to reproduce them. 

2.3.2 may have also corrected the dispatcherServlet issue. The first time I set the default composition I noticed the dispatcherServlet hang on reboot. But after that it never hung again, even after multiple times setting and resetting the default composition. 

The only new step in the process is I updated the PI Imager to the latest version 1.7.5

I'll probably do more testing in a few days. I want to go back and configure another system from scratch to see if I can reproduce the behavior I saw the first time.

**Comment by DavidOpgh** [comment]
![20230621_190720.jpg](https://github.com/moritzvieli/rocketshow/assets/104005724/1eb15c09-74f4-4a51-9b8a-e8467fd17d7f)

OK, I think I found the reason behind one of the new status messages I observed.

 It appears Rocketshow does not like it when a preset in Designer is not attached to a fixture. It was sending a bunch of status messages as shown in the photo.  I created a "nothing" preset that was not attached to anything as pseudo blackout preset.

Once I assigned the "nothing" preset to a fixture the status messages went away.

**Comment by moritzvieli** [comment]
@DavidOpgh Thanks a lot for your detailed tests! I created the following issue regarding the presets without a fixture:
https://github.com/moritzvieli/rocketshow/issues/89

Regarding the servletdispatcher hanging, it's a little difficult to fix, because it never occurs on my system and on yours also only randomly. This could have different causes. I'll include the following suggestion in the next release:
https://stackoverflow.com/questions/53730899/spring-boot-application-stuck-at-initializing-spring-dispatcherservlet-dispatc

Maybe it does a difference.

As for this issue: I consider it solved and close the issue. Thanks again for your effort!

**Comment by DavidOpgh** [comment]
@moritzvieli 
You're welcome. I'm glad to help. 

For other issues can I provide you with more/better data?
Would sending logs be helpful? 
If so,  what level of logging should I set on Rocket Show that would most helpful?
