### ISSUE TITLE
Designer - help with implementation of DMX channels with multiple capabilities

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#94]
@moritzvieli 

Can you provide any assistance whether this is possible or not in Designer.

I'm building my own JSON for Designer to configure my Chauvet Gigbar2 fixture properly and I'm stumped with how to implement a DMX channel with multiple capabilities and some of them have a range of possible values. 
 
I've included the configuration for a "Par 1 Shutter" DMX channel which has 4 capabilities, 2 of which (Intensity and Shutter Strobe) have a range of values the user should be able to select from. If I put this JSON into Designer it implements it as 4 radio selector buttons with no ability to select a particular value. 

I want a "Value" slider be implemented along with the Intensity and Shutter Strobe radio buttons which would allow the user to select a value in that capabilities' particular range.

    "Par 1 Shutter": {
      "capabilities": [
        {
          "dmxRange": [0, 127],
          "type": "Intensity",
          "brightnessStart": "off",
          "brightnessEnd": "bright"
        },
        {
          "dmxRange": [128, 239],
          "type": "ShutterStrobe",
          "shutterEffect": "Strobe",
          "speedStart": "slow",
          "speedEnd": "fast"
        },
        {
          "dmxRange": [240, 249],
          "type": "ShutterStrobe",
          "shutterEffect": "Strobe",
          "soundControlled": true
        },
        {
          "dmxRange": [250, 255],
          "type": "ShutterStrobe",
          "shutterEffect": "Open"
        }
      ]
   },

While looking through the fixture pool and saw the fixture "5Star Systems - Spica 250M" does have some of the functionality I'm looking for. If you select the fixture and look at it in the Channels view selecting the first "Wheel Slot Rotation" under "Gobo rotation" gives you a value slider. 

When I looked at the fixture's JSON it uses the values "angleStart" and "angleEnd". When I replace  "brightnessStart" and  "brightnessEnd" with  "angleStart" and "angleEnd" I get the result I'm looking for, but only for the first capability "Intensity". When I tried to modify the configuration for  "ShutterStrobe" the value slider appeared but didn't allow me to slide through the range of values.

Here is the modified configuration
   "Par 1 Shutter": {
      "capabilities": [
        {
          "dmxRange": [0, 127],
          "type": "Intensity",
          "angleStart": "0%",
          "angleEnd": "100%"
        },
        {
          "dmxRange": [128, 239],
          "type": "ShutterStrobe",
          "angleStart": "0%",
          "angleEnd": "100%"
        },
        {
          "dmxRange": [240, 249],
          "type": "ShutterStrobe",
          "shutterEffect": "Strobe",
          "soundControlled": true
        },
        {
          "dmxRange": [250, 255],
          "type": "ShutterStrobe",
          "shutterEffect": "Open"
        }
      ]
   },

**Comment by moritzvieli** [comment]
@DavidOpgh If you navigate to the rocketshow settings, after upgrading to 2.4.0, there's a new option to select the update branch:

<img width="905" alt="image" src="https://github.com/user-attachments/assets/b0c88e43-951a-4448-99fc-e27bab635c00">

If enabled, you'll see the latest updates, not yet officially released. In this update, I included changes, which rework the channel view. Can you check, whether it works as expected with the ranges for the GigBar 2?

Thanks a lot for your feedback!

**Comment by DavidOpgh** [comment]
I have activated the test-branch and installed the latest update. I have tested the Gigbar2 profile in Designer and have confirmed the channel view works as expected with channels that have ranges for multiple capabilities.

**Comment by moritzvieli** [comment]
@DavidOpgh Great! Thanks for your feedback! I released this version officially and will close this issue.

**Comment by DavidOpgh** [comment]
Excellent! This is going to make the Designer much more useful to users. I didn't check, but has the Fixture Pool been updated as well?

**Comment by moritzvieli** [comment]
Great! Indeed. I just updated the fixture pool as well. 👍

**Comment by DavidOpgh** [comment]
Excellent.  When I have a moment I'll try to update the documentation to include all the latest updates.
