### ISSUE TITLE
How do you turn on / download logging?

### ISSUE THREAD

**Issue by DavidOpgh** [moritzvieli/rocketshow#97]
How do you turn on and download logs?
No matter where I set the "Logging level" at on Settings.System.Advanced nothing happens when I click the download button.

And at looking at Opt/RocketShow folder using WinSCP the logs.zip file is empty.

**Comment by rennist** [comment]
@DavidOpgh   When I access RocketShow from a desktop and click Download Log then it automatically downloaded it into my 'Downloads' folder.as a 'Logs.zip' file... however I just tested this again and it is not working for me now that I updated to 2.3.2.

**Comment by moritzvieli** [comment]
@DavidOpgh @rennist Fixed with 2.3.4, now available in the online updater. Please let me know, if it still does not work. Thanks a lot both! 👍

**Comment by DavidOpgh** [comment]
@moritzvieli 
2.3.4 did not fix the logging issue for me.

**Comment by moritzvieli** [comment]
@DavidOpgh Indeed, there was an additional issue. Just pushed 2.3.5. Does it work now?

**Comment by DavidOpgh** [comment]
@moritzvieli 
2.3.5 seems to have fixed the logging issue.
The status message displayed on the terminal are being written to logs.zip and I'm able to download the logs.zip file.

Can you give any guidelines when it's appropriate to set the logging levels to Debug and Trace?

thanks
David

**Comment by moritzvieli** [comment]
@DavidOpgh Thanks for the info! It's worth a try to set it to trace and see, whether there is more info available in the logs afterwards. But I fear, it does not help in this case.

**Comment by DavidOpgh** [comment]
@moritzvieli 
Thanks for the reply. I'll try it and see what happens. 
Whatever you did to fix the earlier gstreamer issue, can we do more of that?

**Comment by moritzvieli** [comment]
@DavidOpgh I already researched it a little bit but have not found anything of significance. I would give a new try with a new image. But not sure, whether this solves the issue. Otherwise we need to dig deeper.
